language: node_js
sudo: false
node_js:
  - '6.3.1'
env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-templating-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
    # Token for tsd to increase github rate limit
    # See https://github.com/DefinitelyTyped/tsd#tsdrc
    # This does not use http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
    # because those are not visible for pull requests, and those should also be reliable.
    # This SSO token belongs to github account angular-github-ratelimit-token which has no access
    # (password is in Valentine)
    - TSD_GITHUB_TOKEN=ef474500309daea53d5991b3079159a29520a40b

before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce/sauce_connect_setup.sh
  - ./scripts/sauce/sauce_connect_block.sh

script:
  - node_modules/.bin/gulp lint
  - node_modules/.bin/gulp format:enforce
  - node_modules/.bin/gulp build
  - node_modules/.bin/gulp promisetest
  - node_modules/.bin/karma start karma-dist-sauce-jasmine.conf.js --single-run
  - node_modules/.bin/karma start karma-build-sauce-mocha.conf.js --single-run
  - node_modules/.bin/gulp test/node
