language: node_js
sudo: false
dist: trusty
cache: yarn
node_js:
  - 10
env:
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-templating-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
    # Token for tsd to increase github rate limit
    # See https://github.com/DefinitelyTyped/tsd#tsdrc
    # This does not use http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
    # because those are not visible for pull requests, and those should also be reliable.
    # This SSO token belongs to github account angular-github-ratelimit-token which has no access
    # (password is in Valentine)
    - TSD_GITHUB_TOKEN=ef474500309daea53d5991b3079159a29520a40b

before_install:
  - npm install -g yarn
before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/sauce/sauce_connect_setup.sh
  - ./scripts/sauce/sauce_connect_block.sh

script:
  - yarn tslint
  - node_modules/.bin/gulp lint
  - node_modules/.bin/gulp format:enforce
  - node_modules/.bin/gulp filesize
  - scripts/closure/closure_compiler.sh
  - node_modules/.bin/gulp promisetest
  - yarn promisefinallytest
  - yarn build:bazel
  - yarn build:bazel:test
  - rm -rf dist/*.js
  - cp build/bin/npm_package/dist/* dist/
  - rm -rf build
  - yarn tsc
  - node_modules/.bin/karma start karma-dist-sauce-jasmine.conf.js --single-run
  - node_modules/.bin/karma start karma-build-sauce-mocha.conf.js --single-run
  - node_modules/.bin/karma start karma-dist-sauce-selenium3-jasmine.conf.js --single-run
  - node_modules/.bin/karma start karma-build-sauce-selenium3-mocha.conf.js --single-run
  - node_modules/.bin/karma start karma-dist-sauce-jasmine3.conf.js --single-run --errorpolicy=disable
  - node_modules/.bin/karma start karma-dist-sauce-jasmine3.conf.js --single-run --errorpolicy=lazy
  - node_modules/.bin/gulp test/node
  - node_modules/.bin/gulp test/node -no-patch-clock
  - node_modules/.bin/gulp test/bluebird
  - node_modules/.bin/gulp test/node/disableerror
  - node_modules/.bin/gulp test/node/lazyerror
  - node simple-server.js 2>&1> server.log&
  - node ./test/webdriver/test.sauce.js
  - yarn add jasmine@3.0.0 jasmine-core@3.0.0 mocha@5.0.1
  - node_modules/.bin/karma start karma-dist-sauce-jasmine3.conf.js --single-run
  - node_modules/.bin/karma start karma-build-sauce-selenium3-mocha.conf.js --single-run
  - node_modules/.bin/gulp test/node
  - node_modules/.bin/gulp test/node -no-patch-clock
  - cp ./test/browser/custom-element.spec.js ./build/test/browser
  - git checkout .
  - ls build/test
  - node_modules/.bin/karma start karma-evergreen-dist-sauce-jasmine.conf.js --single-run
